import type { Config } from "tailwindcss";

export default {
  darkMode: "class",
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        // Modern Crisp White Themed Foundation
        brand: {
          bg: "var(--brand-bg)",
          surface: "var(--brand-surface)",
          elevated: "var(--brand-elevated)",
          card: "var(--brand-card)",
          border: "var(--brand-border)",
          borderSubtle: "var(--brand-border-subtle)",
          borderStrong: "var(--brand-border-strong)",
          text: "var(--brand-text)",
          muted: "var(--brand-muted)",
          subtle: "var(--brand-subtle)",
        },
        navy: "var(--navy)",
        ink: "var(--ink)",
        muted: "var(--muted)",
        subtle: "var(--subtle)",
        line: "var(--line)",
        lineStrong: "var(--line-strong)",
        surface: "var(--surface)",
        surfaceAlt: "var(--bg-alt)",
        appBg: "var(--bg)",
        upay: {
          DEFAULT: "#0052FF",
          primary: "#0052FF",
          blue: "#0052FF",
          gold: "#D97706",
          amber: "#F59E0B",
          navy: "#0F172A",
          dark: "#0F172A",
          cyan: "#0284C7",
          emerald: "#10B981",
          soft: "rgba(0, 82, 255, 0.08)",
          light: "#EFF6FF",
        },
        risk: {
          critical: "#EF4444",
          criticalSoft: "rgba(239, 68, 68, 0.08)",
          high: "#F97316",
          highSoft: "rgba(249, 115, 22, 0.08)",
          medium: "#F59E0B",
          mediumSoft: "rgba(245, 158, 11, 0.08)",
          low: "#10B981",
          lowSoft: "rgba(16, 185, 129, 0.08)",
          info: "#0052FF",
          infoSoft: "rgba(0, 82, 255, 0.08)",
        },
      },
      fontFamily: {
        sans: [
          "-apple-system",
          "BlinkMacSystemFont",
          '"SF Pro Text"',
          '"SF Pro Display"',
          '"SF Pro"',
          '"SF Pro Icons"',
          '"Hind Siliguri"',
          '"Noto Sans Bengali"',
          "system-ui",
          '"Segoe UI"',
          '"Helvetica Neue"',
          "Helvetica",
          "Arial",
          "sans-serif",
        ],
        display: [
          "-apple-system",
          "BlinkMacSystemFont",
          '"SF Pro Display"',
          '"SF Pro Text"',
          '"SF Pro"',
          '"SF Pro Icons"',
          '"Hind Siliguri"',
          '"Noto Sans Bengali"',
          "system-ui",
          '"Helvetica Neue"',
          "Helvetica",
          "Arial",
          "sans-serif",
        ],
        bangla: [
          '"Hind Siliguri"',
          '"Noto Sans Bengali"',
          "-apple-system",
          "BlinkMacSystemFont",
          "sans-serif",
        ],
        mono: [
          '"SF Mono"',
          "SFMono-Regular",
          "ui-monospace",
          "Menlo",
          "Monaco",
          "Consolas",
          '"Liberation Mono"',
          '"Courier New"',
          "monospace",
        ],
      },
      // STRICT NO-SHADOW CONTRACT: All shadows disabled for flat, high-precision border aesthetic
      boxShadow: {
        none: "none",
        sm: "none",
        DEFAULT: "none",
        md: "none",
        lg: "none",
        xl: "none",
        "2xl": "none",
        card: "none",
        panel: "none",
        elevated: "none",
        modal: "none",
        drawer: "none",
      },
      borderRadius: {
        xs: "4px",
        sm: "6px",
        DEFAULT: "8px",
        md: "8px",
        lg: "10px",
        xl: "12px",
      },
    },
  },
  plugins: [],
} satisfies Config;
