"use client";

import React, { useState } from "react";
import {
  FileText,
  X,
  Download,
  Copy,
  Printer,
  Check,
  ShieldCheck,
  Building,
} from "lucide-react";
import { useSentinel } from "@/context/SentinelContext";

interface ReportExportModalProps {
  isOpen: boolean;
  onClose: () => void;
  onNotify: (msg: string) => void;
}

export const ReportExportModal: React.FC<ReportExportModalProps> = ({
  isOpen,
  onClose,
  onNotify,
}) => {
  const { language, t } = useSentinel();
  const [copied, setCopied] = useState(false);
  const isBn = language === "bn";

  if (!isOpen) return null;

  const reportDate = new Date().toLocaleDateString("en-GB", {
    day: "numeric",
    month: "long",
    year: "numeric",
  });

  const reportTextEn = `================================================================================
BANGLADESH BANK BFIU — SUSPICIOUS TRANSACTION REPORT (STR / SAR)
Generated by: upay Sentinel Risk & Fraud Intelligence Operations
In Compliance With: Money Laundering Prevention Act, 2012 & BFIU Circular 25/2023
================================================================================

Case Reference     : STR-2026-INV1042
Classification     : Coordinated Money-Mule Syndicate & Account Takeover (ATO)
Date & Time        : ${reportDate} · 02:18 AM UTC+6
Primary Suspect    : Customer Wallet 01712-894102 (Tanvir Ahmed)
Target Conduit     : Recipient 01833-883100 (Linked to Syndicate Cluster #17)
Disputed Volume    : ৳48,500 BDT (Cumulative Cluster Exposure: ৳2,840,000 BDT)
Calculated Risk    : 94 / 100 [CRITICAL RISK] · AI Model Confidence: 96%
Lead Analyst       : Arman Hossen (Lead Fraud Analyst, upay SOC)

--------------------------------------------------------------------------------
1. WHAT HAPPENED? (Chronological Transaction Sequence)
--------------------------------------------------------------------------------
At 02:01 AM UTC+6, a previously unobserved mobile hardware fingerprint (DEV-8821,
Samsung S23) authenticated into wallet 01712-894102 from Mirpur-10 cellular node.
- 02:05 AM: A small probing transaction of ৳1,500 was dispatched to verify credentials.
- 02:08 AM: A velocity burst of 3 rapid transfers was executed within 180 seconds.
- 02:13 AM: Primary critical transfer of ৳48,500 was initiated targeting wallet 01833-883100.
- 02:15 AM: Graph network matched recipient 01833-883100 as a layer-1 conduit for
            organized money-mule syndicate Cluster #17 (17 wallets, 43 transactions).

--------------------------------------------------------------------------------
2. WHY IS IT RISKY? (Explainable AI / SHAP Multi-Vector Analysis)
--------------------------------------------------------------------------------
The transaction triggered five statistically independent anomaly flags:
- Amount Vector (92% SHAP): Transfer amount is 4.8× above customer's 30-day baseline (৳6,800).
- Hardware Vector (78% SHAP): DEV-8821 is an unrecognized device with zero history.
- Temporal Vector (74% SHAP): Transacted at 02:13 AM (historic window: 10:00 AM – 09:00 PM).
- Recipient Vector (91% SHAP): Recipient acts as intermediary funneling funds to agent POS.
- Velocity Vector (84% SHAP): 6 transfers across 8 minutes constitutes extreme burst.

--------------------------------------------------------------------------------
3. RECOMMENDED REGULATORY ACTION (BFIU Compliance)
--------------------------------------------------------------------------------
1. Maintain administrative hold on outgoing settlements from recipient 01833-883100.
2. Require live biometric / NID verification from originating wallet 01712-894102.
3. Submit this verified STR dossier directly to Bangladesh Financial Intelligence Unit.
4. Human Oversight: Fund seizures require two-officer authorization per bank charter.

================================================================================
END OF DOSSIER — OFFICIAL MFS REGULATORY SUBMISSION
================================================================================`;

  const reportTextBn = `================================================================================
বাংলাদেশ ব্যাংক বিএফআইইউ — সন্দেহজনক লেনদেন রিপোর্ট (STR / SAR)
প্রস্তুতকারক: উপায় সেন্টিনেল ঝুঁকি ও জালিয়াতি প্রতিরোধ পরিচালনা কেন্দ্র
আইনি ভিত্তি: মানি লন্ডারিং প্রতিরোধ আইন, ২০১২ ও বাংলাদেশ ব্যাংক সার্কুলার ২৫/২০২৩
================================================================================

কেস রেফারেন্স    : STR-2026-INV1042
শ্রেণি           : মানি মিউল সিন্ডিকেট চক্র ও অ্যাকাউন্ট দখল (ATO)
তারিখ ও সময়     : ${reportDate} · ০২:১৮ পূর্বাহ্ন
প্রধান অভিযুক্ত   : গ্রাহক ওয়ালেট ০১৭১২-৮৯৪১০২ (তানভীর আহমেদ)
প্রাপক কন্ডুইট    : প্রাপক ০১৮৩৩-৮৮৩১০০ (মিউল চক্র ১৭-এর সাথে যুক্ত)
সন্দেহভাজন অর্থ  : ৳৪৮,৫০০ টাকা (সিন্ডিকেটের মোট এক্সপোজার: ৳২৮,৪০,০০০ টাকা)
গণনাকৃত ঝুঁকি    : ৯৪ / ১০০ [চরম ঝুঁকিপূর্ণ] · এআই কনফিডেন্স: ৯৬%
প্রধান কর্মকর্তা  : আরমান হোসেন (লিড ফ্রড অ্যানালিস্ট, উপায়)

--------------------------------------------------------------------------------
১. কী ঘটেছে? (ধারাবাহিক লেনদেন বিবরণ)
--------------------------------------------------------------------------------
রাত ০২:০১ টায় একটি অপরিচিত ডিভাইস DEV-8821 (Samsung S23) থেকে ওয়ালেটে প্রবেশ করা হয়।
- ০২:০৫: যাচাইয়ের উদ্দেশ্যে ৳১,৫০০ টাকার একটি ছোট লেনদেন সম্পন্ন হয়।
- ০২:০৮: ১৮০ সেকেন্ডের মধ্যে ৩টি দ্রুতগতির লেনদেন সম্পন্ন করা হয়।
- ০২:১৩: মূল ৳৪৮,৫০০ টাকার বড় স্থানান্তরটি প্রাপক ০১৮৩৩-৮৮৩১০০-এর উদ্দেশ্যে পাঠানো হয়।
- ০২:১৫: গ্রাফ টপোলজি নিশ্চিত করে যে প্রাপক মিউল চক্র ১৭-এর সক্রিয় সদস্য।

--------------------------------------------------------------------------------
২. কেন এটি ঝুঁকিপূর্ণ? (এক্সএআই এবং শ্যাপ বিশ্লেষণ)
--------------------------------------------------------------------------------
- আর্থিক পরিমাণ: স্বাভাবিক ৩০ দিনের হিসাবের তুলনায় ৪.৮ গুণ বেশি।
- ডিভাইস ও সিম: নতুন ডিভাইসে লগইন করার ১২ মিনিটের মাথায় বড় অঙ্কের লেনদেন।
- সময়সূচি: গভীর রাত ০২:১৩ মিনিটে সংঘটিত।
- মিউল নেটওয়ার্ক: প্রাপক একাধিক প্রতারিত অ্যাকাউন্টের টাকা সংগ্রহের হাব।

--------------------------------------------------------------------------------
৩. উপায়ের করণীয় ও রেগুলেটরি সুপারিশ
--------------------------------------------------------------------------------
১. প্রাপক একাউন্টে তহবিল অবমুক্তকরণ অবিলম্বে সাময়িক স্থগিত (Hold) রাখুন।
২. মূল গ্রাহককে ফেসিয়াল বায়োমেট্রিক আঙুলের ছাপ যাচাইয়ের ২এফএ চ্যালেঞ্জ পাঠান।
৩. বাংলাদেশ ব্যাংক বিএফআইইউ-তে সরকারিভাবে এই রিপোর্ট দাখিল করুন।

================================================================================
ডসিয়ার সমাপ্ত — বাংলাদেশ মোবাইল ব্যাংকিং গোয়েন্দা নথি
================================================================================`;

  const activeText = isBn ? reportTextBn : reportTextEn;

  const handleCopy = () => {
    navigator.clipboard.writeText(activeText);
    setCopied(true);
    onNotify(isBn ? "বিএফআইইউ রিপোর্ট ক্লিপবোর্ডে কপি করা হয়েছে।" : "Report copied to clipboard.");
    setTimeout(() => setCopied(false), 2000);
  };

  const handlePrint = () => {
    const printWindow = window.open("", "_blank");
    if (printWindow) {
      printWindow.document.write(`
        <html>
          <head>
            <title>upay Sentinel BFIU STR Report</title>
            <style>
              body { font-family: monospace; font-size: 12px; line-height: 1.4; padding: 20px; white-space: pre-wrap; }
            </style>
          </head>
          <body>${activeText}</body>
        </html>
      `);
      printWindow.document.close();
      printWindow.print();
    }
  };

  return (
    <div className="fixed inset-0 bg-slate-900/40 backdrop-blur-xs z-50 flex items-center justify-center p-4 animate-fadeIn">
      <div className="bg-white border border-slate-200 rounded-xl w-full max-w-3xl max-h-[90vh] flex flex-col overflow-hidden">
        {/* Header */}
        <div className="p-4 border-b border-slate-200 flex items-center justify-between bg-white shrink-0">
          <div className="flex items-center gap-2">
            <div className="w-8 h-8 rounded bg-blue-50 text-blue-600 flex items-center justify-center border border-blue-200">
              <FileText size={16} />
            </div>
            <div>
              <h2 className="text-sm font-bold text-slate-900">
                {t("bfiuReportTitle")}
              </h2>
              <p className="text-[11px] text-slate-500">
                {t("bfiuReportSubtitle")}
              </p>
            </div>
          </div>
          <button
            onClick={onClose}
            className="w-7 h-7 rounded text-slate-400 hover:text-slate-700 hover:bg-slate-100 flex items-center justify-center"
          >
            <X size={16} />
          </button>
        </div>

        {/* Notice banner */}
        <div className="px-4 py-2 bg-amber-50 border-b border-amber-200 text-[11px] text-amber-900 font-mono font-semibold flex items-center gap-2">
          <ShieldCheck size={14} className="text-amber-700 shrink-0" />
          <span>{t("strNotice")}</span>
        </div>

        {/* Text Container */}
        <div className="p-4 overflow-y-auto flex-1 bg-slate-50">
          <pre className="text-[11px] font-mono text-slate-800 leading-relaxed whitespace-pre-wrap select-text p-3 bg-white rounded border border-slate-200">
            {activeText}
          </pre>
        </div>

        {/* Footer actions */}
        <div className="p-3 px-4 border-t border-slate-200 bg-white flex items-center justify-between gap-2 shrink-0">
          <div className="text-[11px] text-slate-500 font-mono">
            {isBn ? "প্রস্তুতকৃত: উপায় সেন্টিনেল এসওসি" : "Signed: upay Sentinel SOC Hub"}
          </div>

          <div className="flex items-center gap-2">
            <button
              onClick={handleCopy}
              className="btn btn-secondary text-xs flex items-center gap-1.5"
            >
              {copied ? <Check size={13} className="text-emerald-600" /> : <Copy size={13} />}
              <span>{copied ? (isBn ? "কপি হয়েছে" : "Copied") : (isBn ? "কপি করুন" : "Copy Text")}</span>
            </button>

            <button
              onClick={handlePrint}
              className="btn btn-primary text-xs flex items-center gap-1.5"
            >
              <Printer size={13} />
              <span>{t("printReport")}</span>
            </button>
          </div>
        </div>
      </div>
    </div>
  );
};
